<a href="https://colab.research.google.com/github/Aravind3991/GUVI_Task/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a = np.array([1,2,3,4,5,6,7])
  
print("Size of array: ",a.size)
  
print("Memory size : ",a.itemsize)

Size of array:  7
Memory size :  8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
a = np.zeros(10)
print(a)
a[4]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
np.arange(10,49)

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x=np.arange(1,10)
print(x)
print(x[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x=[1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3, k=-0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
a=np.random.rand(3,3,3)
print(a)

[[[0.53209773 0.37042136 0.08655062]
  [0.90338329 0.61357669 0.37944406]
  [0.22849816 0.3708399  0.4781988 ]]

 [[0.83405774 0.13775736 0.90997103]
  [0.79498294 0.91841963 0.6459128 ]
  [0.85431839 0.99121135 0.34510811]]

 [[0.05180995 0.06499543 0.70084963]
  [0.94035102 0.30840631 0.54265613]
  [0.1807124  0.07185184 0.828343  ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a=np.random.rand(10,10)
print(np.amin(a))
print(np.amax(a))

0.004502957019156484
0.9915473020140211


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a=np.random.randn(1, 30)
print(np.mean(a))

0.07552125284073874


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a = [1, 2, 3, 4, 5]
print(np.pad(a, (2, 3), 'constant', constant_values=(0, 0)))
print("\n\n")
x = np.ones((5,5))
print(np.pad(x, (2, 3), 'constant', constant_values=(0, 0)))

[0 0 1 2 3 4 5 0 0 0]



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan,"\n",
np.nan == np.nan,"\n",
np.inf > np.nan,"\n",
np.nan - np.nan,"\n",
0.3 == 3 * 0.1)

nan 
 False 
 False 
 nan 
 False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
# arr=np.random.rand(6,7,8)
# print(arr)
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
b = np.array([[1, 0], [0, 1]])

np.tile(b, (8, 8))

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
max, min = x.max(), x.min()
x = (x - min)/(max - min)
print("After normalization:")
print(x)

Original Array:
[[0.44551629 0.43612916 0.22650012 0.61941574 0.88300002]
 [0.90361519 0.88806911 0.41638948 0.64520331 0.41521283]
 [0.95381303 0.33207053 0.75906671 0.96860582 0.14567695]
 [0.97514041 0.07588463 0.17177907 0.94179325 0.87833192]
 [0.18780389 0.92684848 0.38967188 0.30547927 0.80952245]]
After normalization:
[[0.41104173 0.40060296 0.16748904 0.60442326 0.89753706]
 [0.92046176 0.90317404 0.37865184 0.63309982 0.37734337]
 [0.97628329 0.28488657 0.75971942 0.99273333 0.0776112 ]
 [1.         0.         0.10663755 0.96291693 0.89234599]
 [0.12445765 0.94629789 0.34894104 0.25531628 0.81582775]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
np.dtype([('R', np.uint64), ('G', np.int32), ('B', np.int32), ('A', np.int32)])

dtype([('R', '<u8'), ('G', '<i4'), ('B', '<i4'), ('A', '<i4')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x= np.random.random((5,3))
print("X Matrix:")
print(x)
y= np.random.random((3,2))
print("Y matrix:")
print(y)
np.dot(x,y)

X Matrix:
[[0.34340648 0.52746068 0.39635514]
 [0.51451071 0.79121176 0.13245905]
 [0.97917525 0.47008729 0.02615626]
 [0.45353868 0.98038449 0.66740303]
 [0.91675396 0.34605385 0.87147867]]
Y matrix:
[[0.17754253 0.15853536]
 [0.88153335 0.63215544]
 [0.77211524 0.78398871]]


array([[0.83197528, 0.69861717],
       [0.89110073, 0.68558335],
       [0.60843853, 0.47290836],
       [1.46007608, 1.21489375],
       [1.14070279, 1.04732718]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
arr=np.arange(11)
condition = np.logical_and(arr > 2, arr <= 8)
arr = np.select([~condition, condition], [arr, -arr])
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a=np.random.rand(3,3)
print(a)
print("------------------------------")
print(np.copysign(a,-1))
print("------------------------------")
print(np.ceil(a))
print("------------------------------")
print(np.absolute(a))

[[0.42858806 0.10852723 0.10902405]
 [0.68301614 0.55860169 0.35028066]
 [0.58621725 0.49043834 0.84318033]]
------------------------------
[[-0.42858806 -0.10852723 -0.10902405]
 [-0.68301614 -0.55860169 -0.35028066]
 [-0.58621725 -0.49043834 -0.84318033]]
------------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
------------------------------
[[0.42858806 0.10852723 0.10902405]
 [0.68301614 0.55860169 0.35028066]
 [0.58621725 0.49043834 0.84318033]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
ar1=np.arange(1,49)
ar2=np.arange(11,29)

print("------------------------------")
print(ar1)
print("------------------------------")
print(ar2)
print("------------------------------")
print(np.intersect1d(ar1, ar2))

------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
------------------------------
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]
------------------------------
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all='ignore')
np.errstate(divide='ignore')

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(today)
print(yesterday)
print(tomorrow)

2022-06-03
2022-06-02
2022-06-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print(np.arange('2016-07', '2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a=2
b=3
print(np.multiply(np.add(a,b),(np.divide(-a,2))))

-5.0


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print("------------------------------")
print(np.floor(a))
print("------------------------------")
print(np.ceil(a))
print("------------------------------")
print(np.trunc(a))

------------------------------
[-2. -2. -1.  0.  1.  1.  2.]
------------------------------
[-1. -1. -0.  1.  2.  2.  2.]
------------------------------
[-1. -1. -0.  0.  1.  1.  2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a=np.random.randint(0,4, size=(5, 5))
print(a)

[[0 3 0 3 2]
 [2 1 2 3 1]
 [2 2 1 0 0]
 [0 1 0 0 2]
 [1 3 1 3 2]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
iterable = (x for x in range(11))
np.fromiter(iterable, float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0, 1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
arr=np.random.rand(5,2)
print(arr)
np.sort(arr)X = np.arange(8).reshape((2,2,2))
print(X)
np.add.reduce(X, 0)

[[0.39359165 0.12563333]
 [0.61438827 0.15031071]
 [0.07910038 0.06047609]
 [0.96292112 0.04192165]
 [0.87343309 0.47553633]]


array([[0.12563333, 0.39359165],
       [0.15031071, 0.61438827],
       [0.06047609, 0.07910038],
       [0.04192165, 0.96292112],
       [0.47553633, 0.87343309]])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [2]:
X = np.arange(8).reshape((2,2,2))
print(X)
np.add.reduce(X, 0)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[ 4,  6],
       [ 8, 10]])

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [3]:
x=np.random.rand(5,2)
print(x)
y=np.random.rand(5,2)
print(y)
print("------------------------------")
print(np.allclose(x,y))
print("------------------------------")
print(np.array_equal(x,y))

[[0.90291121 0.14387623]
 [0.18550074 0.53564563]
 [0.62987638 0.39073852]
 [0.70952524 0.83837587]
 [0.09541752 0.69532178]]
[[0.84005052 0.13985826]
 [0.17258407 0.390637  ]
 [0.14907243 0.85308063]
 [0.43309434 0.68158593]
 [0.2989463  0.75932059]]
------------------------------
False
------------------------------
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [5]:
x=np.random.rand(10,2)
print(x)

[[0.66687163 0.58460675]
 [0.07256827 0.07669766]
 [0.35246884 0.39141113]
 [0.98174816 0.38169845]
 [0.03595297 0.06937468]
 [0.96113638 0.34517829]
 [0.40619139 0.47006934]
 [0.30328393 0.8870367 ]
 [0.94604097 0.74453435]
 [0.75195173 0.58770133]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [6]:
x=np.random.rand(10,2)
print(x)
print("\nMax element : ", np.argmax(x))
x[np.argmax(x, axis=0)]=0
print(x)

[[0.75816446 0.75666257]
 [0.31720999 0.34796509]
 [0.41231421 0.56682199]
 [0.72562815 0.6575469 ]
 [0.16781492 0.63066001]
 [0.48898034 0.2429901 ]
 [0.53065101 0.43141277]
 [0.88779337 0.5991229 ]
 [0.65396462 0.34950091]
 [0.60643773 0.64569339]]

Max element :  14
[[0.         0.        ]
 [0.31720999 0.34796509]
 [0.41231421 0.56682199]
 [0.72562815 0.6575469 ]
 [0.16781492 0.63066001]
 [0.48898034 0.2429901 ]
 [0.53065101 0.43141277]
 [0.         0.        ]
 [0.65396462 0.34950091]
 [0.60643773 0.64569339]]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [7]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [8]:
np.subtract.outer([1, 2, 3], [4, 5, 6])

array([[-3, -4, -5],
       [-2, -3, -4],
       [-1, -2, -3]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [9]:
ii16 = np.iinfo(np.int16)
print(ii16.min)
print(ii16.max)

-32768
32767


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [10]:
np.set_printoptions(precision=4)
np.array([1.123456789])

array([1.1235])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [12]:
x=np.random.rand(10,2,5)
print(x)
print("\nMin closet element : ", np.argmin(x))

[[[0.3329 0.9604 0.0075 0.6949 0.6816]
  [0.9747 0.7701 0.8401 0.2556 0.353 ]]

 [[0.4381 0.3    0.7491 0.6444 0.8115]
  [0.8591 0.235  0.6522 0.7214 0.0194]]

 [[0.3869 0.9259 0.4676 0.3595 0.0766]
  [0.4526 0.4446 0.9773 0.1132 0.1577]]

 [[0.2974 0.9084 0.0664 0.7793 0.5103]
  [0.954  0.7683 0.431  0.5716 0.8151]]

 [[0.5578 0.0376 0.1648 0.3408 0.4721]
  [0.6319 0.5771 0.1659 0.9698 0.8362]]

 [[0.0765 0.9583 0.735  0.8582 0.994 ]
  [0.3278 0.1511 0.5849 0.5763 0.4793]]

 [[0.9064 0.7494 0.3886 0.0883 0.2117]
  [0.9955 0.671  0.2479 0.1557 0.493 ]]

 [[0.2319 0.1251 0.8342 0.5206 0.9757]
  [0.998  0.0068 0.8814 0.0907 0.9446]]

 [[0.2538 0.9779 0.1223 0.5962 0.6565]
  [0.842  0.1938 0.6251 0.0592 0.9174]]

 [[0.8238 0.6886 0.6329 0.8606 0.4005]
  [0.3184 0.458  0.3547 0.4212 0.6296]]]

Min closet element :  76


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [13]:
x =np.random.rand(100,2)
np.atleast_2d(x)

array([[0.5368, 0.2408],
       [0.5742, 0.5462],
       [0.9412, 0.4593],
       [0.1283, 0.9069],
       [0.2699, 0.5785],
       [0.5471, 0.3484],
       [0.2925, 0.1613],
       [0.8048, 0.198 ],
       [0.2931, 0.6312],
       [0.264 , 0.0759],
       [0.3583, 0.3282],
       [0.6361, 0.9603],
       [0.4856, 0.6599],
       [0.6311, 0.4948],
       [0.2619, 0.4283],
       [0.5127, 0.5505],
       [0.9103, 0.9772],
       [0.1957, 0.0921],
       [0.9601, 0.1475],
       [0.0674, 0.4124],
       [0.717 , 0.9248],
       [0.0101, 0.9433],
       [0.5247, 0.6285],
       [0.7045, 0.6726],
       [0.2546, 0.0694],
       [0.5943, 0.2993],
       [0.6619, 0.9355],
       [0.0077, 0.568 ],
       [0.8814, 0.8895],
       [0.8138, 0.1707],
       [0.9801, 0.4113],
       [0.0129, 0.2721],
       [0.7639, 0.0434],
       [0.2911, 0.2444],
       [0.6743, 0.7182],
       [0.3252, 0.9075],
       [0.7087, 0.803 ],
       [0.8604, 0.3875],
       [0.6304, 0.0075],
       [0.6612, 0.8063],


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [14]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [15]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
print(xv)
print(yv)

[[0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0. 0. 0.]
 [1. 1. 1.]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [16]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
print(a)

[-44   1 -55   3   4]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [17]:
x=np.random.rand(10,2)
print(x)
np.mean(x, axis=1)

[[0.0629 0.4132]
 [0.6408 0.568 ]
 [0.0352 0.5468]
 [0.0347 0.4804]
 [0.6054 0.2854]
 [0.8661 0.9201]
 [0.9966 0.1239]
 [0.0731 0.8865]
 [0.7999 0.1274]
 [0.648  0.9125]]


array([0.238 , 0.6044, 0.291 , 0.2576, 0.4454, 0.8931, 0.5603, 0.4798,
       0.4636, 0.7803])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [18]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [19]:
x=np.random.rand(10,2)
print(x)
np.any(np.nan)

[[0.1447 0.622 ]
 [0.2219 0.0947]
 [0.04   0.973 ]
 [0.6886 0.1003]
 [0.8493 0.6235]
 [0.4641 0.2099]
 [0.669  0.7695]
 [0.2437 0.8596]
 [0.2033 0.9082]
 [0.6354 0.0743]]


True

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [20]:
x=np.random.rand(10,2)
abs(x)

array([[0.2772, 0.9175],
       [0.0803, 0.7477],
       [0.4062, 0.0712],
       [0.6687, 0.2982],
       [0.7906, 0.051 ],
       [0.1435, 0.7163],
       [0.8476, 0.4623],
       [0.4   , 0.4495],
       [0.9967, 0.9645],
       [0.4036, 0.1512]])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [21]:
import numpy as np

arr = np.array([[[1, 3], [3, 1]]])
sum=0
for x in np.nditer(arr):
  sum=sum+x
print(sum)

8


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
ypoints = np.array([3, 8, 1, 10])
plt.plot(ypoints, color = #4CAF50 )
plt.show()

SyntaxError: ignored

In [ ]:
import numpy as np

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

i = np.argsort(student_id)

print(i[5])

5


In [ ]:
import pandas as pd

import numpy as np

s = pd.Series(np.random.randn(4))

print(s)

print(s.ndim)

0    0.389758
1   -0.168744
2    0.612644
3    0.449369
dtype: float64
1


In [ ]:
a = np.array([[1,2,3],[0,1,4]])

b = np.zeros((2,3), dtype=np.int16)

c = np.ones((2,3), dtype=np.int16)

d = a + b + c

print(d)

print (d[1,2] )

[[2 3 4]
 [1 2 5]]
5


In [ ]:
import numpy as np

a = np.array([1,2,3])

print (a)

[1 2 3]


In [ ]:
import numpy as np

from numpy import linalg

a = np.array([[1, 0], [1, 2]])

print(type(np.linalg.det(a)))

<class 'numpy.float64'>


In [ ]:

s = pd.Series (np.random.randn(87))

print(s.ndim)

1
