<a href="https://colab.research.google.com/github/Aravind3991/GUVI_Task/blob/main/Numpy_tasks_Aravind.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a = np.array([1,2,3,4,5,6,7])
  
print("Size of array: ",a.size)
  
print("Memory size : ",a.itemsize)

Size of array:  7
Memory size :  8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
a = np.zeros(10)
print(a)
a[4]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
np.arange(10,49)

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x=np.arange(1,10)
print(x)
print(x[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x=[1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3, k=-0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
a=np.random.rand(3,3,3)
print(a)

[[[0.53209773 0.37042136 0.08655062]
  [0.90338329 0.61357669 0.37944406]
  [0.22849816 0.3708399  0.4781988 ]]

 [[0.83405774 0.13775736 0.90997103]
  [0.79498294 0.91841963 0.6459128 ]
  [0.85431839 0.99121135 0.34510811]]

 [[0.05180995 0.06499543 0.70084963]
  [0.94035102 0.30840631 0.54265613]
  [0.1807124  0.07185184 0.828343  ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a=np.random.rand(10,10)
print(np.amin(a))
print(np.amax(a))

0.004502957019156484
0.9915473020140211


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a=np.random.randn(1, 30)
print(np.mean(a))

0.07552125284073874


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a = [1, 2, 3, 4, 5]
print(np.pad(a, (2, 3), 'constant', constant_values=(0, 0)))
print("\n\n")
x = np.ones((5,5))
print(np.pad(x, (2, 3), 'constant', constant_values=(0, 0)))

[0 0 1 2 3 4 5 0 0 0]



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan,"\n",
np.nan == np.nan,"\n",
np.inf > np.nan,"\n",
np.nan - np.nan,"\n",
0.3 == 3 * 0.1)

nan 
 False 
 False 
 nan 
 False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
# arr=np.random.rand(6,7,8)
# print(arr)
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
b = np.array([[1, 0], [0, 1]])

np.tile(b, (8, 8))

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
max, min = x.max(), x.min()
x = (x - min)/(max - min)
print("After normalization:")
print(x)

Original Array:
[[0.44551629 0.43612916 0.22650012 0.61941574 0.88300002]
 [0.90361519 0.88806911 0.41638948 0.64520331 0.41521283]
 [0.95381303 0.33207053 0.75906671 0.96860582 0.14567695]
 [0.97514041 0.07588463 0.17177907 0.94179325 0.87833192]
 [0.18780389 0.92684848 0.38967188 0.30547927 0.80952245]]
After normalization:
[[0.41104173 0.40060296 0.16748904 0.60442326 0.89753706]
 [0.92046176 0.90317404 0.37865184 0.63309982 0.37734337]
 [0.97628329 0.28488657 0.75971942 0.99273333 0.0776112 ]
 [1.         0.         0.10663755 0.96291693 0.89234599]
 [0.12445765 0.94629789 0.34894104 0.25531628 0.81582775]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
np.dtype([('R', np.uint64), ('G', np.int32), ('B', np.int32), ('A', np.int32)])

dtype([('R', '<u8'), ('G', '<i4'), ('B', '<i4'), ('A', '<i4')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x= np.random.random((5,3))
print("X Matrix:")
print(x)
y= np.random.random((3,2))
print("Y matrix:")
print(y)
np.dot(x,y)

X Matrix:
[[0.34340648 0.52746068 0.39635514]
 [0.51451071 0.79121176 0.13245905]
 [0.97917525 0.47008729 0.02615626]
 [0.45353868 0.98038449 0.66740303]
 [0.91675396 0.34605385 0.87147867]]
Y matrix:
[[0.17754253 0.15853536]
 [0.88153335 0.63215544]
 [0.77211524 0.78398871]]


array([[0.83197528, 0.69861717],
       [0.89110073, 0.68558335],
       [0.60843853, 0.47290836],
       [1.46007608, 1.21489375],
       [1.14070279, 1.04732718]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
arr=np.arange(11)
condition = np.logical_and(arr > 2, arr <= 8)
arr = np.select([~condition, condition], [arr, -arr])
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a=np.random.rand(3,3)
print(a)
print("------------------------------")
print(np.copysign(a,-1))
print("------------------------------")
print(np.ceil(a))
print("------------------------------")
print(np.absolute(a))

[[0.42858806 0.10852723 0.10902405]
 [0.68301614 0.55860169 0.35028066]
 [0.58621725 0.49043834 0.84318033]]
------------------------------
[[-0.42858806 -0.10852723 -0.10902405]
 [-0.68301614 -0.55860169 -0.35028066]
 [-0.58621725 -0.49043834 -0.84318033]]
------------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
------------------------------
[[0.42858806 0.10852723 0.10902405]
 [0.68301614 0.55860169 0.35028066]
 [0.58621725 0.49043834 0.84318033]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
ar1=np.arange(1,49)
ar2=np.arange(11,29)

print("------------------------------")
print(ar1)
print("------------------------------")
print(ar2)
print("------------------------------")
print(np.intersect1d(ar1, ar2))

------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
------------------------------
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]
------------------------------
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all='ignore')
np.errstate(divide='ignore')

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(today)
print(yesterday)
print(tomorrow)

2022-06-03
2022-06-02
2022-06-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print(np.arange('2016-07', '2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a=2
b=3
print(np.multiply(np.add(a,b),(np.divide(-a,2))))

-5.0


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print("------------------------------")
print(np.floor(a))
print("------------------------------")
print(np.ceil(a))
print("------------------------------")
print(np.trunc(a))

------------------------------
[-2. -2. -1.  0.  1.  1.  2.]
------------------------------
[-1. -1. -0.  1.  2.  2.  2.]
------------------------------
[-1. -1. -0.  0.  1.  1.  2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a=np.random.randint(0,4, size=(5, 5))
print(a)

[[0 3 0 3 2]
 [2 1 2 3 1]
 [2 2 1 0 0]
 [0 1 0 0 2]
 [1 3 1 3 2]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
iterable = (x for x in range(11))
np.fromiter(iterable, float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0, 1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
arr=np.random.rand(5,2)
print(arr)
np.sort(arr)X = np.arange(8).reshape((2,2,2))
print(X)
np.add.reduce(X, 0)

[[0.39359165 0.12563333]
 [0.61438827 0.15031071]
 [0.07910038 0.06047609]
 [0.96292112 0.04192165]
 [0.87343309 0.47553633]]


array([[0.12563333, 0.39359165],
       [0.15031071, 0.61438827],
       [0.06047609, 0.07910038],
       [0.04192165, 0.96292112],
       [0.47553633, 0.87343309]])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
X = np.arange(8).reshape((2,2,2))
print(X)
np.add.reduce(X, 0)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[ 4,  6],
       [ 8, 10]])

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
x=np.random.rand(5,2)
print(x)
y=np.random.rand(5,2)
print(y)
print("------------------------------")
print(np.allclose(x,y))
print("------------------------------")
print(np.array_equal(x,y))

[[0.90291121 0.14387623]
 [0.18550074 0.53564563]
 [0.62987638 0.39073852]
 [0.70952524 0.83837587]
 [0.09541752 0.69532178]]
[[0.84005052 0.13985826]
 [0.17258407 0.390637  ]
 [0.14907243 0.85308063]
 [0.43309434 0.68158593]
 [0.2989463  0.75932059]]
------------------------------
False
------------------------------
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
x=np.random.rand(10,2)
print(x)

[[0.66687163 0.58460675]
 [0.07256827 0.07669766]
 [0.35246884 0.39141113]
 [0.98174816 0.38169845]
 [0.03595297 0.06937468]
 [0.96113638 0.34517829]
 [0.40619139 0.47006934]
 [0.30328393 0.8870367 ]
 [0.94604097 0.74453435]
 [0.75195173 0.58770133]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x=np.random.rand(10,2)
print(x)
print("\nMax element : ", np.argmax(x))
x[np.argmax(x, axis=0)]=0
print(x)

[[0.75816446 0.75666257]
 [0.31720999 0.34796509]
 [0.41231421 0.56682199]
 [0.72562815 0.6575469 ]
 [0.16781492 0.63066001]
 [0.48898034 0.2429901 ]
 [0.53065101 0.43141277]
 [0.88779337 0.5991229 ]
 [0.65396462 0.34950091]
 [0.60643773 0.64569339]]

Max element :  14
[[0.         0.        ]
 [0.31720999 0.34796509]
 [0.41231421 0.56682199]
 [0.72562815 0.6575469 ]
 [0.16781492 0.63066001]
 [0.48898034 0.2429901 ]
 [0.53065101 0.43141277]
 [0.         0.        ]
 [0.65396462 0.34950091]
 [0.60643773 0.64569339]]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
np.subtract.outer([1, 2, 3], [4, 5, 6])

array([[-3, -4, -5],
       [-2, -3, -4],
       [-1, -2, -3]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
ii16 = np.iinfo(np.int16)
print(ii16.min)
print(ii16.max)

-32768
32767


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(precision=4)
np.array([1.123456789])

array([1.1235])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x=np.random.rand(10,2,5)
print(x)
print("\nMin closet element : ", np.argmin(x))

[[[0.3329 0.9604 0.0075 0.6949 0.6816]
  [0.9747 0.7701 0.8401 0.2556 0.353 ]]

 [[0.4381 0.3    0.7491 0.6444 0.8115]
  [0.8591 0.235  0.6522 0.7214 0.0194]]

 [[0.3869 0.9259 0.4676 0.3595 0.0766]
  [0.4526 0.4446 0.9773 0.1132 0.1577]]

 [[0.2974 0.9084 0.0664 0.7793 0.5103]
  [0.954  0.7683 0.431  0.5716 0.8151]]

 [[0.5578 0.0376 0.1648 0.3408 0.4721]
  [0.6319 0.5771 0.1659 0.9698 0.8362]]

 [[0.0765 0.9583 0.735  0.8582 0.994 ]
  [0.3278 0.1511 0.5849 0.5763 0.4793]]

 [[0.9064 0.7494 0.3886 0.0883 0.2117]
  [0.9955 0.671  0.2479 0.1557 0.493 ]]

 [[0.2319 0.1251 0.8342 0.5206 0.9757]
  [0.998  0.0068 0.8814 0.0907 0.9446]]

 [[0.2538 0.9779 0.1223 0.5962 0.6565]
  [0.842  0.1938 0.6251 0.0592 0.9174]]

 [[0.8238 0.6886 0.6329 0.8606 0.4005]
  [0.3184 0.458  0.3547 0.4212 0.6296]]]

Min closet element :  76


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
x =np.random.rand(100,2)
np.atleast_2d(x)

array([[0.5368, 0.2408],
       [0.5742, 0.5462],
       [0.9412, 0.4593],
       [0.1283, 0.9069],
       [0.2699, 0.5785],
       [0.5471, 0.3484],
       [0.2925, 0.1613],
       [0.8048, 0.198 ],
       [0.2931, 0.6312],
       [0.264 , 0.0759],
       [0.3583, 0.3282],
       [0.6361, 0.9603],
       [0.4856, 0.6599],
       [0.6311, 0.4948],
       [0.2619, 0.4283],
       [0.5127, 0.5505],
       [0.9103, 0.9772],
       [0.1957, 0.0921],
       [0.9601, 0.1475],
       [0.0674, 0.4124],
       [0.717 , 0.9248],
       [0.0101, 0.9433],
       [0.5247, 0.6285],
       [0.7045, 0.6726],
       [0.2546, 0.0694],
       [0.5943, 0.2993],
       [0.6619, 0.9355],
       [0.0077, 0.568 ],
       [0.8814, 0.8895],
       [0.8138, 0.1707],
       [0.9801, 0.4113],
       [0.0129, 0.2721],
       [0.7639, 0.0434],
       [0.2911, 0.2444],
       [0.6743, 0.7182],
       [0.3252, 0.9075],
       [0.7087, 0.803 ],
       [0.8604, 0.3875],
       [0.6304, 0.0075],
       [0.6612, 0.8063],


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
print(xv)
print(yv)

[[0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0. 0. 0.]
 [1. 1. 1.]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
print(a)

[-44   1 -55   3   4]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x=np.random.rand(10,2)
print(x)
np.mean(x, axis=1)

[[0.0629 0.4132]
 [0.6408 0.568 ]
 [0.0352 0.5468]
 [0.0347 0.4804]
 [0.6054 0.2854]
 [0.8661 0.9201]
 [0.9966 0.1239]
 [0.0731 0.8865]
 [0.7999 0.1274]
 [0.648  0.9125]]


array([0.238 , 0.6044, 0.291 , 0.2576, 0.4454, 0.8931, 0.5603, 0.4798,
       0.4636, 0.7803])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x=np.random.rand(10,2)
print(x)
np.any(np.nan)

[[0.1447 0.622 ]
 [0.2219 0.0947]
 [0.04   0.973 ]
 [0.6886 0.1003]
 [0.8493 0.6235]
 [0.4641 0.2099]
 [0.669  0.7695]
 [0.2437 0.8596]
 [0.2033 0.9082]
 [0.6354 0.0743]]


True

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x=np.random.rand(10,2)
abs(x)

array([[0.2772, 0.9175],
       [0.0803, 0.7477],
       [0.4062, 0.0712],
       [0.6687, 0.2982],
       [0.7906, 0.051 ],
       [0.1435, 0.7163],
       [0.8476, 0.4623],
       [0.4   , 0.4495],
       [0.9967, 0.9645],
       [0.4036, 0.1512]])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
import numpy as np

arr = np.array([[[1, 3], [3, 1]]])
sum=0
for x in np.nditer(arr):
  sum=sum+x
print(sum)

8


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

aray = NamedArray(np.arange(10), "range_10")
print (aray.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(Z)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 3 6 5 5 9 3 5 0 0 8 5 2 1 2 6 5 2 9 1]
[3. 4. 4. 3. 1. 6. 3. 1. 2. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(X,I)
print(F)

[0. 1. 3. 9. 3. 4. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))

print(sum)

[[60 56 28 59]
 [63 40 62 64]
 [55 88 51 64]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.54340757 0.38276985 0.55136917 0.5103105  0.52286805 0.5134085
 0.42885672 0.43334522 0.522537   0.33916678]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.36505779, 1.53780825, 1.2446557 , 0.67656995, 1.09466277])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
x = np.array([1,2,3,4,5])
nx = 3
x_new = np.zeros(len(x) + (len(x)-1)*(nx))
x_new[::nx+1] = x
print(x_new)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 26) ( 0, 99) ( 7, 23) ( 7, 62) ( 9, 58) ( 9, 99) (17, 20) (17, 74)
 (20, 74) (23, 62) (26, 99) (41, 49) (41, 92) (49, 56) (49, 89) (49, 92)
 (50, 68) (50, 94) (54, 57) (54, 66) (56, 89) (57, 66) (58, 99) (68, 94)
 (78, 96) (88, 95) (88, 97) (95, 97) (96, 96)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
x = np.random.randint(0,2,100)
np.logical_not(x, out=x)

x = np.random.uniform(-1.0,1.0,100)
np.negative(x, out=x)

array([ 0.69681259, -0.29219464, -0.14401028,  0.63078774, -0.93929573,
        0.75118693, -0.97163281,  0.27531413, -0.28698182, -0.49667907,
        0.56752313, -0.00834626,  0.82400768, -0.01607028,  0.22818638,
        0.58535062,  0.33597641, -0.35198607, -0.25846323,  0.61241597,
       -0.64161784,  0.38411849, -0.71813999,  0.88092117,  0.6698468 ,
       -0.59211344,  0.07226687,  0.36496431, -0.32167541,  0.97544694,
        0.49583024,  0.56462387, -0.58629575,  0.9596553 , -0.15796847,
       -0.9857543 , -0.33843004, -0.92771102,  0.75824742, -0.85081141,
       -0.48292673, -0.9853098 ,  0.00504196,  0.08258804, -0.11769581,
       -0.85828   , -0.31949249,  0.85102499,  0.56626963, -0.67860778,
        0.4782438 , -0.22124388, -0.77563885,  0.87499318,  0.32683704,
        0.95863464, -0.22639348, -0.38424109, -0.65888607,  0.1611496 ,
       -0.49077193, -0.94351876, -0.8662695 , -0.29059748, -0.55191716,
       -0.69314797,  0.25846773, -0.39354362,  0.41238326,  0.93

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[11.7670403   8.49717056  1.24546289  1.23625047  6.16342838 13.49954653
  8.77068362  3.42149221  0.44928014  6.39848463]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.38131896  0.59361926  5.65355842  6.74971637  5.09499628  0.22857207
   5.48179707  5.01208462  7.08229318  4.00768584]
 [ 2.76129278  0.12797905  5.61216428  3.95669857  2.34898638  2.45352547
   8.50166268  7.60116148  4.53422284  5.92621381]
 [ 6.8777725   2.51757901  3.48899647  0.58301189  2.18787842  3.84885501
  12.95923003  9.75217805  2.47410242  6.75060471]
 [ 7.92306345  1.68282623  7.901816    0.37325538  1.09032132  7.83912502
  12.88991987 13.26721988  1.10685231 11.00172047]
 [ 7.88109254  4.58652577 10.8472854   1.6647926   0.28418316  9.97170617
  12.13522922 14.99820387  2.89130852 13.37973639]
 [10.84054842  6.51373358  0.02800155  5.58060937  7.22455243  4.11046074
  17.60769458 10.93970886  1.40054776  6.34186559]
 [ 0.23828151  1.92013749  7.02145036  7.20597628  5.59227855  1.33559589
   5.28697615  5.9511478   6.1204795   5.2130187 ]
 [ 0.58038523  3.83224576  1.12787933  4.99804161  3.21180246  3.2372577
   6.38895246  2.13323475 10.03992589  0.1901622 ]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 4 1 0 8 8 2 5 6 0]
 [8 7 3 7 0 6 3 9 3 2]
 [2 8 1 7 0 9 2 5 6 5]
 [5 9 3 5 9 8 1 4 8 3]
 [1 0 3 6 4 4 1 2 2 8]
 [9 1 6 4 7 2 5 5 1 0]
 [5 8 0 7 3 6 4 6 9 8]
 [6 1 2 2 3 5 2 1 4 1]
 [2 2 0 6 1 7 7 7 0 2]
 [9 0 9 1 9 7 3 8 5 9]]
[[0 0 0 0 0]
 [0 0 4 1 0]
 [0 8 7 3 7]
 [0 2 8 1 7]
 [0 5 9 3 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
x = np.array([3,1,2,1,3,3])
np.bincount(x).argmax()

3

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 2 1]
   [2 0 0]
   [1 4 1]]

  [[2 1 0]
   [0 0 2]
   [4 1 0]]

  [[1 0 3]
   [0 2 3]
   [1 0 0]]

  [[0 3 1]
   [2 3 4]
   [0 0 0]]

  [[3 1 4]
   [3 4 4]
   [0 0 3]]

  [[1 4 1]
   [4 4 1]
   [0 3 2]]

  [[4 1 1]
   [4 1 0]
   [3 2 1]]

  [[1 1 1]
   [1 0 3]
   [2 1 1]]]


 [[[2 0 0]
   [1 4 1]
   [1 0 1]]

  [[0 0 2]
   [4 1 0]
   [0 1 4]]

  [[0 2 3]
   [1 0 0]
   [1 4 1]]

  [[2 3 4]
   [0 0 0]
   [4 1 1]]

  [[3 4 4]
   [0 0 3]
   [1 1 2]]

  [[4 4 1]
   [0 3 2]
   [1 2 4]]

  [[4 1 0]
   [3 2 1]
   [2 4 2]]

  [[1 0 3]
   [2 1 1]
   [4 2 2]]]


 [[[1 4 1]
   [1 0 1]
   [2 4 4]]

  [[4 1 0]
   [0 1 4]
   [4 4 3]]

  [[1 0 0]
   [1 4 1]
   [4 3 2]]

  [[0 0 0]
   [4 1 1]
   [3 2 0]]

  [[0 0 3]
   [1 1 2]
   [2 0 1]]

  [[0 3 2]
   [1 2 4]
   [0 1 0]]

  [[3 2 1]
   [2 4 2]
   [1 0 3]]

  [[2 1 1]
   [4 2 2]
   [0 3 2]]]


 [[[1 0 1]
   [2 4 4]
   [3 4 2]]

  [[0 1 4]
   [4 4 3]
   [4 2 0]]

  [[1 4 1]
   [4 3 2]
   [2 0 2]]

  [[4 1 1]
   [3 2 0]
   [0 2 2]]

  [[1 1 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  4 11 12 14]
 [ 4  4  8  8 15]
 [11  8  9 42  4]
 [12  8 42  1 14]
 [14 15  4 14  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 5, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
x = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
                                       np.arange(0, x.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
x = np.array([1,5,3,9,8,7])
x.argsort()
#x[np.argpartition(x, 2)]


array([0, 2, 1, 5, 4, 3])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
x = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(x.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(5)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

The slowest run took 25.09 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.03 µs per loop
The slowest run took 17.61 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.19 µs per loop
The slowest run took 19.75 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.89 µs per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
x = np.random.randint(0,5,(10,3))
print(x)
E = np.all(x[:,1:] == x[:,:-1], axis=1)
U = x[~E]
print(U)

[[4 2 2]
 [0 1 2]
 [1 4 2]
 [1 1 3]
 [3 4 1]
 [1 2 4]
 [0 0 1]
 [2 1 4]
 [0 1 2]
 [0 2 4]]
[[4 2 2]
 [0 1 2]
 [1 4 2]
 [1 1 3]
 [3 4 1]
 [1 2 4]
 [0 0 1]
 [2 1 4]
 [0 1 2]
 [0 2 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B) 

array([[0.19499769, 0.16753007, 0.41603943, 0.55638027, 0.38316983,
        0.50918983, 0.57302783, 0.56704321, 0.35241386, 0.17848063],
       [0.32964574, 0.28321143, 0.70331922, 0.94056696, 0.64775281,
        0.860791  , 0.96870984, 0.95859277, 0.5957595 , 0.30172346],
       [0.2215499 , 0.19034211, 0.47269018, 0.63214079, 0.43534484,
        0.57852458, 0.65105519, 0.64425567, 0.40040093, 0.20278376],
       [0.2951316 , 0.253559  , 0.62968122, 0.84208895, 0.57993264,
        0.77066559, 0.86728525, 0.85822745, 0.53338307, 0.27013281],
       [0.23831429, 0.20474504, 0.50845802, 0.67997404, 0.4682868 ,
        0.62230076, 0.70031967, 0.69300563, 0.43069873, 0.21812814],
       [0.21736247, 0.18674453, 0.46375605, 0.62019295, 0.42711656,
        0.56759011, 0.63874985, 0.63207884, 0.39283311, 0.19895103],
       [0.2134536 , 0.18338626, 0.45541623, 0.60903988, 0.41943563,
        0.55738301, 0.62726307, 0.62071203, 0.3857687 , 0.19537325],
       [0.02369536, 0.0203576 , 0.0505554

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)
y_int
x_int

array([ 0.00000000e+00, -3.73131229e-01, -2.59817608e+00, -3.26212050e+00,
       -2.18442687e+00, -2.98929946e-02,  2.42923642e+00,  4.54913599e+00,
        5.92318348e+00,  6.35117933e+00,  5.82369277e+00,  4.46259540e+00,
        2.47320794e+00,  1.09577220e-01, -2.36575300e+00, -4.71261671e+00,
       -6.72701769e+00, -8.25541575e+00, -9.18486120e+00, -9.46381505e+00,
       -9.11085788e+00, -8.12875279e+00, -6.63306046e+00, -4.69271059e+00,
       -2.44736165e+00, -2.05444585e-02,  2.46101146e+00,  4.86841760e+00,
        7.08937968e+00,  9.02539126e+00,  1.05948609e+01,  1.17357250e+01,
        1.24068974e+01,  1.25885805e+01,  1.22815267e+01,  1.15053927e+01,
        1.02963689e+01,  8.70429550e+00,  6.78948686e+00,  4.61716636e+00,
        2.25853448e+00, -1.98731680e-01, -2.68040566e+00, -5.11543300e+00,
       -7.41973991e+00, -9.53891040e+00, -1.14237629e+01, -1.29919305e+01,
       -1.42355069e+01, -1.51243232e+01, -1.56061571e+01, -1.57219415e+01,
       -1.54217066e+01, -

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) 
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.42681948  0.03193792]
